bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
  userName: Marandyuk_Anatolii


server:
  port: 8080
  host: "https://overridetech.ru/review-report-bot"

reminders:
  maxDaysWithoutReport: 3

pay-info:
  login: ${LIFE_PAY_LOGIN:root}
  apikey: ${LIFE_PAY_KEY:root}
  method: sbp

spring:
  application:
    name: review-bot
  datasource:
    password: ${POSTGRES_PASSWORD:root}
    username: ${POSTGRES_USER:root}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${TELEGRAM_BOT_DB_PORT:5432}/review_bot
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: com.nekromant.telegram.utils.CustomDialectUtils # org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

lombok:
  accessors:
    chain: true

schedulePeriod:
  start: 18
  end: 3

logging:
  level:
    org.zalando.logbook: TRACE

